### ISSUE TITLE
Add Hints

### ISSUE THREAD

**Issue by sakshi2912** [triambaka/Hangman#1]
Add a timer within which the user should guess the right word.
Create a time limit based on the word length.
Example : 7 Letters - 2 minutes.

**Comment by Prajwal2204** [comment]
hey can I work on this?

**Comment by sakshi2912** [comment]
> hey can I work on this?

Go ahead

**Comment by shreya-panale** [comment]
I would like to try this

**Comment by sakshi2912** [comment]
> I would like to try this

Sure, you can. But you would not be getting the same bounty as mentioned in the label, it would reduce , one because this is  not the first PR , second ,it depends on the code you submit.

So if you think it's worth doing, you can go ahead.
