### ISSUE TITLE
[DOCUMENTATION] Create a README

### ISSUE THREAD

**Issue by srujandeshpande** [triambaka/Hangman#10]
**Describe the solution you'd like**
Create a README.md file and include the following information in it:
1. Name of the repo
2. What it does
3. How to install and run the code

Any more information will result in a higher bounty!

**Comment by shreya-panale** [comment]
I would like to do this

**Comment by sakshi2912** [comment]
> I would like to do this

Go ahead! It would be better if you can include some screenshots as well

**Comment by shreya-panale** [comment]
> > I would like to do this
> 
> Go ahead! It would be better if you can include some screenshots as well

I will add it now

**Comment by shreya-panale** [comment]
@sakshi2912 ,can you check it? and close the PR

**Comment by RakshithRAcharya** [comment]
Can I do this?? @srujandeshpande

**Comment by sakshi2912** [comment]
> Can I do this?? @srujandeshpande

Yeah

**Comment by RakshithRAcharya** [comment]
@sakshi2912 bounty points??

**Comment by sakshi2912** [comment]
> @sakshi2912 bounty points??

Has to be manually updated, will be done in a while
